### ISSUE TITLE
Android usage

### ISSUE THREAD

**Issue by formatBCE** [ayaromenok/Android_ImageMagick7#26]
Hi!
First of all - thank you for your work - seems to be amazing!
But there's no explanation, how to use it with Android - just link to non-existing  https://github.com/paulasiimwe/Android-ImageMagick

How can i get java interface for it?
Thank you in advance.

**Comment by ayaromenok** [comment]
Looks like owner of ImageMagick6 port to Android(@paulasiimwe), which was also include Java interface, just delete his repository :(

**Comment by formatBCE** [comment]
Yup, so question is, where should i start from with it - can i use JMagick, or something similar?
Sorry for dumb questions - i'm just newbie with native... ;(

**Comment by ayaromenok** [comment]
Looks like JMagick is a thin JNI interface for ImageMagick 6 (6.5.7 - 9 years old) and PC Linux\Windows, so require a ImageMagick6 libs build on you system. 

Since December of last year it include a some code to support a 7 version too (which is used in this repo), but looks like not finished yet (well, I can't even build it now). I will try to build it - maybe it's a useful addition to code from this repo, but it would be fast (I didn't use Java for 15+ years ;))

added as a separate issue #27

**Comment by formatBCE** [comment]
Yeah, looks like there's no open-source builds for Java/Android now across the Internet, so it would be REALLY helpful :)
Thank you in advance!
Anyway, i will try to use JMagick by myself... Though 9 years looks damn old...

**Comment by ayaromenok** [comment]
JMagick - it's just a interface, so you need a ImageMagick6 build(i.e. android\linux shared libraries for arm at leat) for android any way

**Comment by formatBCE** [comment]
Yes, I suspect. But it should be available to be built with Android NDK...

**Comment by paulasiimwe** [comment]
I've republished the repo. 
Goodluck.

**Comment by formatBCE** [comment]
@paulasiimwe You're the best!

**Comment by ayaromenok** [comment]
@paulasiimwe thank you! 
@formatBCE I close this issue for now
