### ISSUE TITLE
cant find convert binary for android

### ISSUE THREAD

**Issue by TonyStark** [ayaromenok/Android_ImageMagick7#28]
Hi
i hve downloaded latest binary from release page
but i cant find `convert` binary file
is that missing?

**Comment by ayaromenok** [comment]
it's a two parts:

### General
ImageMagick on Win\Linux\Mac have only one binary - `magick`. `convert` and other it's just a sym-links to `magick` (with exception of windows\FAT, where symlinks not supported and it's just a copy-rename of `magick`).  You probably asking about missing `magick` binary.

### Android-related
Application is sand-boxed, so building and deploying command-line `magick` binary to Android almost useless, since user can't use it anyway. Well, on rooted phone via terminal emulator\adb shell it's probably possible.

If you still need `magick` binary, it's two options:
 - use older release - https://github.com/ayaromenok/Android_ImageMagick7/releases/tag/v0.3.7052 . `magick`  placed in corresponding library directory
- uncomment `include $(BUILD_EXECUTABLE)`  line in the end of jni/Android.mk.openmp (line 517) and rebuild ImageMagick

PS: if you know a good scenario of direct use `magick`/`convert` on android - please inform me - I will include binary again.

**Comment by TonyStark** [comment]
Thank you 
i found exactly what i want :)
anyway there is no direct use, only by using terminal or adb shell
my program can work on terminal only, so i need imagemagick binary.
if other user want to use then here is quick example
just put both `.so` file in `/system/lib64`
and `magick` file in `/system/bin`
`#> magick in.png -crop 1025x300+25+800 out.jpg`
--Closing Issue :)

**Comment by ayaromenok** [comment]
I re-upload latest release with `magick` utility in each compiler\arch folder and it will be build by default in future.

BTW, you can't push anything to `/system/bin` or `/system/lib64` since it's typically not only protected for writing (you can change it in rooted phone), but also have control of firmware modification (on Samsung Galaxy phones, like most popular Android phone in the world) - so this trick only for developer firmware\phone :)

**Comment by TonyStark** [comment]
yeah, it need rooted phone.
however it does not process some png file somehow ;x

**Comment by ayaromenok** [comment]
probably, it would be a good idea to create a separate issue with this specific png files - I can check with `MagickCore` and `MagickWand` libs (but not with `magick` utility itself)
