### ISSUE TITLE
Compile into Executable Binary

### ISSUE THREAD

**Issue by u3amar** [ayaromenok/Android_ImageMagick7#7]
Can you compile this into an executable binary, similar to what ffmpeg does? I'm running into a lot of compilation issues when trying to do so myself.

**Comment by ayaromenok** [comment]
You can find library binaries for all supported platforms at github release page https://github.com/ayaromenok/Android_ImageMagick7/releases/tag/v0.2.7052 or directly in source tree https://github.com/ayaromenok/Android_ImageMagick7/tree/master/libs

Building ImageMagick application itself (i.e. magick and sym-links to convert, animate, display, compare, etc) have very little sense for Android since it will be possible to use it only from terminal with command-line options (like Terminal Emulator app or adb shell). also, it need Activity to start

**Comment by u3amar** [comment]
Can you build it anyways? It's possible to run an executable using Process.run(), which would make life a lot easier for people who have ImageMagick command-line code.

**Comment by ayaromenok** [comment]
Please find a **magick** binary in corresponding architecture directory at https://github.com/ayaromenok/Android_ImageMagick7/tree/master/libs starting from  3492a53 

- don't forget to add MagickCore/MagickWand libs to linker path to allow **magick** app to load it
- **animate**,  **composite**,  **convert**,  **identify** etc utilities from ImageMagick it's just a symlinks to **magick**, so `convert logo: rose: -morph 15 my%02dmorph.jpg` should be changed to  `magick logo: rose: -morph 15 my%02dmorph.jpg`
- default imageMagick resources not included
